include:
  - project: 'meat-n-potatoes/ci'
    file: 'all.yml'
    ref: v2

stages:
  - lint
  - build
  - test
  - publish

lint:
  extends: .node-lint
  stage: lint

build:
  extends: .node-build
  stage: build

test:
  extends: .node-test
  stage: test

sync-github-repo:
  extends: .sync-github-repo
  stage: publish
  only: [master]
  variables:
    GITHUB_SSH_URL: git@github.com:servall/app-config.git
