# Our Gitlab CI is internal to Launchcode - see TravisCI file for public releases!

include:
  - project: 'meat-n-potatoes/ci'
    file: 'all.yml'
    ref: v2

stages:
  - lint
  - build
  - test

lint:
  extends: .node-lint
  stage: lint

build:
  extends: .node-build
  stage: build

test:
  extends: .node-test
  stage: test

publish:
  extends: .node-publish-tag
  stage: publish
