name: standalone-project

on:
  push:
    branches: 'master'
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [14.x]

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        working-directory: ./tests/standalone-project

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    # run cli without installing once, as a sanity check for fresh install
    - run: npx @app-config/cli -v

    - run: yarn install
    - run: yarn build
    - run: node ./dist/index.js
    - run: yarn app-config -v
    - run: yarn app-config c
