name: standalone-project

on:
  push:
    branches: 'master'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [14.x]

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        working-directory: ./tests/standalone-project

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - run: yarn install && yarn build
      working-directory: ./app-config

    - run: find . -name node_modules -exec rm -rf {} \;
      working-directory: .

    - run: yarn install
    - run: yarn build
    - run: node ./dist/index.js
